checks:
  php:
    code_rating: true

filter:
  excluded_paths:
    - phpstan/*
    - tests/*
    - vendor/*

build:

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    custom-nodes:
      services:
        custom-mysql:
          image: docker.io/library/mysql:5.7
          env:
            MYSQL_DATABASE: testing
            MYSQL_USER: testing
            MYSQL_PASSWORD: testing
            MYSQL_ROOT_PASSWORD: testing
          ports:
            - 3306

  environment:
    php: '7.4'
    docker: true

  dependencies:
    before:
      - composer install
      - mkdir -p build/logs

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover build/logs/clover.xml'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
