version: 'Compose-Spec'

services:

  php:
    image: joseluisq/php-fpm:8.1
    volumes:
      - .:/code:cached
    working_dir: /code
    entrypoint: ['tail', '-f', '/dev/null']
    command: []

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: testing
 