version: '3'

services:

  php:
    image: circleci/php:7.3
    volumes:
      - .:/code:cached
    command:
      sh -c '
        sudo docker-php-ext-install pdo_mysql;
        cd /code;
        tail -F /dev/null;
      '

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
