version: '3'

services:

  php:
    image: circleci/php:7.4
    volumes:
      - .:/code:cached
    command:
      sh -c '
        sudo docker-php-ext-install pdo_mysql;
        cd /code;
        tail -F /dev/null;
      '

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: testing
