name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - '3306:3306'
        env:
          MYSQL_DATABASE: testing
          MYSQL_USER: testing
          MYSQL_PASSWORD: testing
          MYSQL_ROOT_PASSWORD: testing
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=30s
          --health-retries=5

    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [^11.0, ^12.0, ^13.0.x-dev]
        exclude:
          - php: 8.2
            laravel: ^13.0.x-dev
        include:
          - php: 8.2
            php-cs-fixer: 1
          - php: 8.3
            php-cs-fixer: 1
          - laravel: ^11.0
            larastan: 1
          - laravel: ^12.0
            larastan: 1

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Remove impossible dependencies (nunomaduro/larastan)
        if: ${{ matrix.larastan != 1 }}
        run: composer remove nunomaduro/larastan --dev --no-update

      - name: Remove impossible dependencies (friendsofphp/php-cs-fixer)
        if: ${{ matrix.php-cs-fixer != 1 }}
        run: composer remove friendsofphp/php-cs-fixer --dev --no-update

      - name: Adjust Package Versions
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --dev --no-update
          composer update

      - name: Prepare Coverage Directory
        run: mkdir -p build/logs

      - name: PHP-CS-Fixer
        if: ${{ matrix.php-cs-fixer == 1 }}
        run: composer cs

      - name: PHPStan
        if: ${{ matrix.larastan == 1 }}
        run: composer phpstan

      - name: Test
        run: composer test -- --testdox --coverage-clover build/logs/clover.xml

      - name: Upload Coverage
        uses: nick-invision/retry@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: 'true'
          COVERALLS_FLAG_NAME: "laravel:${{ matrix.laravel }} php:${{ matrix.php }}"
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v

  coverage-aggregation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
